# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Continuous Integration

on:
#  workflow_dispatch: 
  push:
     branches:
      - feat/ci-cd

env:
  MAVEN_PARAM: --batch-mode
  CVSS_TOLERANCE: 4

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
   
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up maven cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Git code checkout
      uses: actions/checkout@v3

    - name: Code compile
      run: mvn $MAVEN_PARAM clean compile
      
    - name: Unit test
      run: mvn $MAVEN_PARAM test
          
    - name: Acceptance test
      run: mvn $MAVEN_PARAM jbehave:run-stories-as-embeddables@run-stories-as-embeddables

    - name: Integration test
      run: mvn $MAVEN_PARAM verify failsafe:integration-test
      
    - name: Code analysis
      run: |
        mvn $MAVEN_PARAM sonar:sonar -Dsonar.host.url=https://sonarcloud.io \
                                    -Dsonar.qualitygate.wait=true \
                                    -Dsonar.login="${{ secrets.SONAR_LOGIN_KEY }}" \
                                    -Dsonar.organization="${{ secrets.SONAR_ORG }}" \
                                    -Dsonar.projectKey="${{ secrets.SONAR_PROJ }}"
                        
    - name: Dependency scan
      run: mvn $MAVEN_PARAM dependency-check:check -DfailBuildOnCVSS=$CVSS_TOLERANCE
    
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6











